id = "faber"
name = "Faber"
description = "Latin programming language support for Zed."
version = "0.1.0"
schema_version = 1
authors = ["Ian Zepp <ianzepp@gmail.com>"]
repository = "https://github.com/ianzepp/tree-sitter-faber"

[grammars.faber]
repository = "https://github.com/ianzepp/tree-sitter-faber"
rev = "96ca64695a985799ff0c5ac1cb192a2f9112447e"
